### ISSUE TITLE
Cannot find module '@actions/core' in v1.0.2

### ISSUE THREAD

**Issue by eliasbalasis** [lablnet/create-branch-from-tag#6]
**Describe the bug**

```
node:internal/modules/cjs/loader:[10](https://github.com/.../.../actions/runs/7725079122/job/21058552793#step:3:11)51
  throw err;
  ^

Error: Cannot find module '@actions/core'
Require stack:
- /opt/actions-runner/_work/_actions/lablnet/create-branch-from-tag/v1.0.2/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:[11](https://github.com/.../.../actions/runs/7725079122/job/21058552793#step:3:12)15:19)
    at require (node:internal/modules/helpers:[13](https://github.com/.../.../actions/runs/7725079122/job/21058552793#step:3:14)0:18)
    at 734 (/opt/actions-runner/_work/_actions/lablnet/create-branch-from-tag/v1.0.2/dist/index.js:71:33)
    at __nccwpck_require__ (/opt/actions-runner/_work/_actions/lablnet/create-branch-from-tag/v1.0.2/dist/index.js:1[14](https://github.com/.../.../actions/runs/7725079122/job/21058552793#step:3:15):42)
    at [26](https://github.com/.../.../actions/runs/7725079122/job/21058552793#step:3:27)5 (/opt/actions-runner/_work/_actions/lablnet/create-branch-from-tag/v1.0.2/dist/index.js:7:14)
    at __nccwpck_require__ (/opt/actions-runner/_work/_actions/lablnet/create-branch-from-tag/v1.0.2/dist/index.js:114:42)
    at /opt/actions-runner/_work/_actions/lablnet/create-branch-from-tag/v1.0.2/dist/index.js:133:13
    at /opt/actions-runner/_work/_actions/lablnet/create-branch-from-tag/v1.0.2/dist/index.js:139:3 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/actions-runner/_work/_actions/lablnet/create-branch-from-tag/v1.0.2/dist/index.js'
  ]
```

**To Reproduce**

Run the action and observe the log

**Expected behavior**

No errors

**Screenshots**

Not applicable

**Desktop (please complete the following information):**

Not applicable

**Smartphone (please complete the following information):**

Not applicable

**Additional context**

**Comment by lablnet** [comment]
Fixed in `v1.0.4` But you need to update your workflow to add permission

```yml
    permissions: # Read more at : https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      contents: write
```

See updated example in `Readme.md`
